services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/dockerfile
    entrypoint: ./scripts/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - "./.env.dev"
    depends_on:
      - db
    networks:
      - project-net

  db:
    image : mysql     
    container_name : 'mysql_container'       
    ports : 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$(ROOT_PASS)
    volumes:
      - mysql-django:/var/lib/mysql/
    networks:
      - project-net
      
networks:
  project-net:

volumes:
  mysql-django:
