version: '3.1'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/dockerfile

    ports:
      - "8000:8000"
    
    env_file:
      - ",/,env.dev"
    

networks:
  project-net:

